repositories:
- name: jenkins
  url: https://charts.jenkins.io

helmDefaults:
  atomic: true
  timeout: 180
  wait: true

releases:
- name: jenkins-extra
  chart: ./charts/jenkins-extra
  namespace: {{ .Values.namespace }}
  values:
  - charts/jenkins-extra/values.yaml.gotmpl
- name: jenkins
  chart: jenkins/jenkins
  version: ~3.3.4
  namespace: {{ .Values.namespace }}
  needs:
  - {{ .Values.namespace }}/jenkins-extra
  values:
  - charts/jenkins/values.yaml.gotmpl
  - charts/jenkins/values-agent.yaml.gotmpl
  - charts/jenkins/values-casc-credentials.yaml.gotmpl
  - charts/jenkins/values-casc-jenkins.yaml.gotmpl
  - charts/jenkins/values-casc-jobs.yaml.gotmpl
  - charts/jenkins/values-casc-unclassified.yaml.gotmpl

environments:
  # The default environment is used for staging.
  default:
    values:
    - environments/common.yaml
    - environments/staging.yaml
  production:
    values:
    - environments/common.yaml
    - environments/production.yaml
