{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chartmuseum.fullname" . }}
  labels:
    "app.kubernetes.io/name": {{ template "chartmuseum.fullname" . }}
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
  annotations:
    "meta.helm.sh/release-name": "{{ .Release.Name }}"
    "meta.helm.sh/release-namespace": {{ .Values.namespace }}
{{- end -}}
