podTemplates:
  workingDir: "/home/jenkins"
  imagePullSecretName: "kubernetes-docker-cfg"
  serviceAccount: "jenkins"
  nodeUsageMode: EXCLUSIVE
  privileged: true
  ttyEnabled: true
  containers:
  - args: "^${computer.jnlpmac} ^${computer.name}"
    command: ""
    image: "jenkins/inbound-agent:4.3-4"
    name: "jnlp"
    resourceRequestCpu: "100m"
    resourceRequestMemory: "128Mi"
    workingDir: "/home/jenkins"
  envVars:
  - envVar:
      key: "DOCKER_CONFIG"
      value: "/home/jenkins/.docker/"
  - envVar:
      key: "GIT_AUTHOR_EMAIL"
      value: "platform+jx-bot@nuxeo.com"
  - envVar:
      key: "GIT_AUTHOR_NAME"
      value: "nuxeo-platform-jx-bot"
  - envVar:
      key: "GIT_COMMITTER_EMAIL"
      value: "platform+jx-bot@nuxeo.com"
  - envVar:
      key: "GIT_COMMITTER_NAME"
      value: "nuxeo-platform-jx-bot"
  - envVar:
      key: "XDG_CONFIG_HOME"
      value: "/home/jenkins"
  volumes:
  - hostPathVolume:
      hostPath: "/var/run/docker.sock"
      mountPath: "/var/run/docker.sock"
  - secretVolume:
      mountPath: "/home/jenkins/.docker"
      secretName: "jenkins-docker-cfg"
  nodeSelector: "team=platform"
  yamlMergeStrategy: "override"
  yaml: |-
    apiVersion: v1
    kind: Pod
    spec:
      tolerations:
      - key: team
        operator: Equal
        value: platform
        effect: NoSchedule
jobs:
  traits:
    gitHubBranchDiscovery: |-
      // Discover branches
      gitHubBranchDiscovery {
        // Strategy: Exclude branches that are also filed as PRs
        strategyId(1)
      }
    gitHubPullRequestDiscovery: |-
      // Discover pull requests from origin
      gitHubPullRequestDiscovery {
        // Strategy: The current pull request revision
        strategyId(2)
      }
    disableStatusUpdateTrait: |-
      // Disable GitHub Notifications
      disableStatusUpdateTrait()
    masterHeadRegexFilter: |-
      // Filter by name (with regular expression)
      headRegexFilter {
        // Regular expression
        regex('master|PR-.*')
      }
    ltsHeadRegexFilter: |-
      // Filter by name (with regular expression)
      headRegexFilter {
        // Regular expression
        regex('2021|PR-.*')
      }
    mainHeadRegexFilter: |-
      // Filter by name (with regular expression)
      headRegexFilter {
        // Regular expression
        regex('main|PR-.*')
      }
  orphanedItemStrategy: |-
    // Orphaned Item Strategy
    orphanedItemStrategy {
      // Discard old items
      discardOldItems {
      }
    }