podTemplates:
  workingDir: "/home/jenkins"
  imagePullSecretName: "kubernetes-docker-cfg"
  serviceAccount: "jenkins"
  nodeUsageMode: EXCLUSIVE
  privileged: true
  ttyEnabled: true
  containers:
  - args: "^${computer.jnlpmac} ^${computer.name}"
    command: ""
    image: "jenkins/inbound-agent:4.3-4"
    name: "jnlp"
    resourceRequestCpu: "100m"
    resourceRequestMemory: "128Mi"
    workingDir: "/home/jenkins"
  - args: ""
    command: ""
    image: docker:dind
    name: dind-daemon
    privileged: true
    resourceRequestCpu: "20m"
    resourceRequestMemory: "512Mi"
    workingDir: "/home/jenkins"
  envVars:
  - envVar:
      key: DOCKER_CERT_PATH
      value: "/certs/client"
  - envVar:
      key: "DOCKER_CONFIG"
      value: "/home/jenkins/.docker/"
  - envVar:
      key: DOCKER_HOST
      value: "tcp://localhost:2376"
  - envVar:
      key: DOCKER_TLS_VERIFY
      value: 1
  - envVar:
      key: "GIT_AUTHOR_EMAIL"
      value: "platform+jx-bot@nuxeo.com"
  - envVar:
      key: "GIT_AUTHOR_NAME"
      value: "nuxeo-platform-jx-bot"
  - envVar:
      key: "GIT_COMMITTER_EMAIL"
      value: "platform+jx-bot@nuxeo.com"
  - envVar:
      key: "GIT_COMMITTER_NAME"
      value: "nuxeo-platform-jx-bot"
  - envVar:
      key: "XDG_CONFIG_HOME"
      value: "/home/jenkins"
  - envVar:
      key: "JENKINS_URL"
      value: "http://jenkins:8080"
  javaEnvVars:
  - envVar:
      key: "JAVA_TOOL_OPTIONS"
      value: "-Dsun.zip.disableMemoryMapping=true
        -XX:+UseParallelGC
        -XX:MinHeapFreeRatio=5
        -XX:MaxHeapFreeRatio=10
        -XX:GCTimeRatio=4
        -XX:AdaptiveSizePolicyWeight=90"
  mavenEnvVars:
  - envVar:
      key: "MAVEN_OPTS"
      value: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
  redisEnvVars:
  - envVar:
      key: "ALLOW_EMPTY_PASSWORD"
      value: "yes"
  volumes:
  - emptyDirVolume:
      mountPath: /certs
  - emptyDirVolume:
      mountPath: /var/lib/docker
  - configMapVolume:
      configMapName: "docker-dind-daemon"
      mountPath: "/etc/docker/daemon.json"
      subPath: "daemon.json"
  - secretVolume:
      mountPath: "/home/jenkins/.docker"
      secretName: "jenkins-docker-cfg"
  mavenSettingsVolumes:
  - secretVolume:
      mountPath: "/root/.m2"
      secretName: "jenkins-maven-settings"
  mavenRepositoryVolumes:
  - emptyDirVolume:
      memory: false
      mountPath: "/root/.mvnrepository"
  nodeSelector: "team=platform"
  yamlMergeStrategy: "override"
  yaml: |-
    apiVersion: v1
    kind: Pod
    spec:
      tolerations:
      - key: team
        operator: Equal
        value: platform
        effect: NoSchedule
jobs:
  traits:
    gitHubBranchDiscovery: |-
      // Discover branches
      gitHubBranchDiscovery {
        // Strategy: Exclude branches that are also filed as PRs
        strategyId(1)
      }
    gitHubPullRequestDiscovery: |-
      // Discover pull requests from origin
      gitHubPullRequestDiscovery {
        // Strategy: The current pull request revision
        strategyId(2)
      }
    disableStatusUpdateTrait: |-
      // Disable GitHub Notifications
      disableStatusUpdateTrait()
    masterHeadRegexFilter: |-
      // Filter by name (with regular expression)
      headRegexFilter {
        // Regular expression
        regex('master|PR-.*')
      }
    ltsHeadRegexFilter: |-
      // Filter by name (with regular expression)
      headRegexFilter {
        // Regular expression
        regex('2021|2023|PR-.*')
      }
    mainHeadRegexFilter: |-
      // Filter by name (with regular expression)
      headRegexFilter {
        // Regular expression
        regex('main|PR-.*')
      }
  orphanedItemStrategy: |-
    // Orphaned Item Strategy
    orphanedItemStrategy {
      // Discard old items
      discardOldItems {
      }
    }
  properties:
    disableConcurrentBuilds: |-
      disableConcurrentBuilds {
        abortPrevious(false)
      }