namespace: platform
dryrun: false
jenkins:
  url: https://jenkins.platform.dev.nuxeo.com/
docker:
  registry: docker.platform.dev.nuxeo.com
github:
  credentialsId: "github"
jira:
  url: https://jira.nuxeo.com/
jobs:
  traits:
    headRegexFilter: |-
      // Filter by name (with regular expression)
      headRegexFilter {
        // Regular expression
        regex('master|PR-.*')
      }
    ltsHeadRegexFilter: |-
      // Filter by name (with regular expression)
      headRegexFilter {
        // Regular expression
        regex('2021|PR-.*')
      }
  triggers: |-
    // Scan Repository Triggers
    triggers {
      // Periodically if not otherwise run
      periodicFolderTrigger {
        // Interval
        interval('5m')
      }
    }