namespace: platform
dryrun: false
ingressNginx:
  enabled: true
buildKit:
  hpa:
    minReplicas: 4
    maxReplicas: 8
certManager:
  enabled: true
datadog:
  enabled: true
docker:
  registry: docker.platform.dev.nuxeo.com
nexus:
  persistence:
    storageSize: 1Ti
  resources:
    # Ratio: node CPU (32) and memory (64) / 2
    cpu: 2
    memory: 32
podTemplates:
  yaml:
    metadata:
      labels:
        dev.nuxeo.com/initiator: jenkins-platform
jobs:
  strategy: |-
    // Property strategy
    strategy {
      // All branches get the same properties
      allBranchesSame {
      }
    }
  traits:
    releaseGitHubPullRequestDiscovery: |-
    releaseMasterHeadRegexFilter: |-
      // Filter by name (with regular expression)
      headRegexFilter {
        // Regular expression
        regex('master')
      }
    releaseLtsHeadRegexFilter: |-
      // Filter by name (with regular expression)
      headRegexFilter {
        // Regular expression
        regex('2023|2025')
      }
    releaseMainHeadRegexFilter: |-
      // Filter by name (with regular expression)
      headRegexFilter {
        // Regular expression
        regex('main')
      }
  triggers: |-
    // Scan Repository Triggers
    triggers {
      // Periodically if not otherwise run
      periodicFolderTrigger {
        // Interval
        interval('1d')
      }
    }
  arenderHelmChartUpdater:
    triggers: |-
      pipelineTriggers {
        // Build Triggers
        triggers {
          // Build periodically
          cron {
            // Schedule
            spec('H 2 * * 1')
          }
        }
      }
  benchmarkNuxeoLTS:
    triggers: |-
      pipelineTriggers {
        // Build Triggers
        triggers {
          // Build periodically
          parameterizedCron {
            // Schedule
            parameterizedSpecification('''
              H 1 * * 1 % NUXEO_BRANCH=2023 ; NUXEO_DOCKER_IMAGE=docker-private.packages.nuxeo.com/nuxeo/nuxeo-benchmark:2023.x ; INSTALL_NEEDED_PACKAGES=false
              H 1 * * 1 % NUXEO_BRANCH=2025 ; NUXEO_DOCKER_IMAGE=docker-private.packages.nuxeo.com/nuxeo/nuxeo-benchmark:2025.x ; INSTALL_NEEDED_PACKAGES=false
            ''')
          }
        }
      }
  cleanupExports:
    triggers: |-
      pipelineTriggers {
        // Build Triggers
        triggers {
          // Build periodically
          cron {
            // Schedule
            spec('H H(8-10) * * *')
          }
        }
      }
  mirrorNuxeoLTS:
    triggers: |-
      pipelineTriggers {
        // Build Triggers
        triggers {
          // Build periodically
          parameterizedCron {
            // Schedule
            parameterizedSpecification('''
              H 1 * * * % NUXEO_LTS_BRANCH=2023
              H 1 * * * % NUXEO_LTS_BRANCH=2025
            ''')
          }
        }
      }
  scanDockerImageNuxeoLTS:
    triggers: |-
      pipelineTriggers {
        // Build Triggers
        triggers {
          // Build periodically
          parameterizedCron {
            // Schedule
            parameterizedSpecification('''
              H 2 * * * % NUXEO_BRANCH=2023
              H 2 * * * % NUXEO_BRANCH=2025
            ''')
          }
        }
      }
  serverWebUIIntegrationTests:
    triggers: |-
      pipelineTriggers {
        // Build Triggers
        triggers {
          // Build periodically
          cron {
            // Schedule
            spec('H 1 * * *')
          }
        }
      }
  deletePreviewNamespaces:
    triggers: |-
      pipelineTriggers {
        // Build Triggers
        triggers {
          // Build periodically
          cron {
            // Schedule
            spec('H 1 * * 6')
          }
        }
      }
  properties:
    buildDiscarder: |-
      buildDiscarder {
        strategy {
          logRotator {
            daysToKeepStr('60')
            numToKeepStr('60')
            artifactDaysToKeepStr('')
            artifactNumToKeepStr('5')
          }
        }
      }
    buildDiscarderLongTime: |-
      buildDiscarder {
        strategy {
          logRotator {
            daysToKeepStr('365')
            numToKeepStr('')
            artifactDaysToKeepStr('')
            artifactNumToKeepStr('')
          }
        }
      }
awsCredentialsRotation: true
nfs:
  enabled: true
