namespace: platform-staging
dryrun: true
ingressNginx:
  enabled: false
buildKit:
  hpa:
    minReplicas: 1
    maxReplicas: 4
certManager:
  enabled: false
datadog:
  enabled: false
docker:
  registry: docker.platform-staging.dev.nuxeo.com
node:
  dist:
    registry: nexus.platform-staging.dev.nuxeo.com/repository/nodejs-upstream/
  npm:
    registry: nexus.platform-staging.dev.nuxeo.com/repository/npmjs-registry/
nexus:
  persistence:
    storageSize: 256Gi
  resources:
    # Ratio: node CPU (8) and memory (64) / 8
    cpu: 1
    memory: 8
podTemplates:
  yaml:
    metadata:
      labels:
        dev.nuxeo.com/initiator: jenkins-platform-staging
jobs:
  strategy: |-
    // Property strategy
    strategy {
      // All branches get the same properties
      allBranchesSame {
        props {
          // Suppress automatic SCM triggering
          suppressAutomaticTriggering()
        }
      }
    }
  traits:
    releaseGitHubPullRequestDiscovery: |-
      // Discover pull requests from origin
      gitHubPullRequestDiscovery {
        // Strategy: The current pull request revision
        strategyId(2)
      }
    releaseMasterHeadRegexFilter: |-
      // Filter by name (with regular expression)
      headRegexFilter {
        // Regular expression
        regex('master|PR-.*')
      }
    releaseLtsHeadRegexFilter: |-
      // Filter by name (with regular expression)
      headRegexFilter {
        // Regular expression
        regex('2023|2025|PR-.*')
      }
    releaseMainHeadRegexFilter: |-
      // Filter by name (with regular expression)
      headRegexFilter {
        // Regular expression
        regex('main|PR-.*')
      }
  triggers: |-
    // Scan Repository Triggers
    triggers {
    }
  arenderHelmChartUpdater:
    triggers: |-
      pipelineTriggers {
        // Build Triggers
        triggers {
        }
      }
  arenderScanDockerImages:
    triggers: |-
      pipelineTriggers {
        // Build Triggers
        triggers {
        }
      }
  benchmarkNuxeoLTS:
    triggers: |-
      pipelineTriggers {
        // Build Triggers
        triggers {
        }
      }
  cleanupExports:
    triggers: |-
      pipelineTriggers {
        // Build Triggers
        triggers {
        }
      }
  mirrorNuxeoLTS:
    triggers: |-
      pipelineTriggers {
        // Build Triggers
        triggers {
        }
      }
  scanDockerImageNuxeoLTS:
    triggers: |-
      pipelineTriggers {
        // Build Triggers
        triggers {
        }
      }
  serverWebUIIntegrationTests:
    triggers: |-
      pipelineTriggers {
        // Build Triggers
        triggers {
        }
      }
  deletePreviewNamespaces:
    triggers: |-
      pipelineTriggers {
        // Build Triggers
        triggers {
        }
      }
  properties:
    buildDiscarder: |-
      buildDiscarder {
        strategy {
          logRotator {
            daysToKeepStr('7')
            numToKeepStr('3')
            artifactDaysToKeepStr('')
            artifactNumToKeepStr('3')
          }
        }
      }
    buildDiscarderLongTime: |-
      buildDiscarder {
        strategy {
          logRotator {
            daysToKeepStr('7')
            numToKeepStr('3')
            artifactDaysToKeepStr('')
            artifactNumToKeepStr('3')
          }
        }
      }
# Don't run in platform-staging namespace to avoid double key rotation
awsCredentialsRotation: false
nfs:
  enabled: false
