namespace: platform-staging
dryrun: true
docker:
  registry: docker.platform-staging.dev.nuxeo.com
github:
  credentialsId: ""
jira:
  url: https://jira-preprod.nuxeo.com/
jobs:
  strategy: |-
    // Property strategy
    strategy {
      // All branches get the same properties
      allBranchesSame {
        props {
          // Suppress automatic SCM triggering
          suppressAutomaticTriggering()
        }
      }
    }
  triggers: |-
    // Scan Repository Triggers
    triggers {
    }
  cleanupExports:
    triggers: |-
      // Build Triggers
      triggers {
      }
  mirrorNuxeoLTS:
    triggers: |-
      pipelineTriggers {
        // Build Triggers
        triggers {
        }
      }
  serverWebUIIntegrationTests:
    triggers: |-
      pipelineTriggers {
        // Build Triggers
        triggers {
        }
      }
# Don't run in platform-staging namespace to avoid double key rotation
awsCredentialsRotation: false