namespace: platform-staging
dryrun: true
jenkins:
  url: https://jenkins.platform-staging.dev.nuxeo.com/
docker:
  registry: docker.platform-staging.dev.nuxeo.com
github:
  credentialsId: ""
jira:
  url: https://jira-preprod.nuxeo.com/
jobs:
  traits:
    headRegexFilter: |-
      // Filter by name (with regular expression)
      headRegexFilter {
        // Regular expression
        regex('master')
      }
    ltsHeadRegexFilter: |-
      // Filter by name (with regular expression)
      headRegexFilter {
        // Regular expression
        regex('2021')
      }
  triggers: |-
    // Scan Repository Triggers
    triggers {
    }