apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.service.name }}
  labels:
    app.kubernetes.io/name: jenkins-master
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.ingress.annotations }}
  annotations: {{ toYaml .Values.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: {{ .Values.ingress.service.name }}
          servicePort: {{ .Values.ingress.service.port }}
        {{- with .Values.ingress.path }}
        path: {{ toYaml . }}
        {{- end }}
    {{- with .Values.ingress.hostname }}
    host: {{ toYaml . }}
    {{- end }}
  {{- with .Values.ingress.tls }}
  tls: {{- toYaml . | nindent 4 }}
  {{- end }}
