apiVersion: v1
kind: ConfigMap
metadata:
  name: buildkitd-config
  labels:
    app.kubernetes.io/name: skaffold-builder-multiplatform
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  buildkitd.toml: | {{ .Values.config.buildkitd | nindent 4 }}
