apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: aws-credentials-rotator
spec:
  suspend: {{ .Values.cronjob.suspend }}
  schedule: {{ .Values.cronjob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            parent: aws-credentials-rotator
        spec:
          containers:
          - name: aws-credentials-rotator
            image: {{ .Values.cronjob.image }}
          restartPolicy: Never
          serviceAccount: aws-credentials-updater
          serviceAccountName: aws-credentials-updater
          nodeSelector:
            team: platform
          tolerations:
          - key: team
            operator: Equal
            value: platform
            effect: NoSchedule
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
