apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  annotations:
    meta.helm.sh/release-name: aws-credentials
    meta.helm.sh/release-namespace: {{ .Values.secret.namespace }}
  labels:
    "app.kubernetes.io/managed-by": Helm
    aws-rotate-key: "true"
stringData:
  access_key_id: {{ .Values.secret.accessKeyId }}
  secret_access_key: {{ .Values.secret.secretAccessKey }}
