apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-dind-daemon
  labels:
    app.kubernetes.io/name: jenkins
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  daemon.json: | {{ .Values.configMap.dockerDind.daemon | nindent 4 }}
