apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-buildx
  labels:
    app.kubernetes.io/name: jenkins
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.configMap.dockerBuildx.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  skaffold-builder-multiplatform: | {{ .Values.configMap.dockerBuildx.skaffoldBuilderMultiplatform | nindent 4 }}
  current: | {{ .Values.configMap.dockerBuildx.currentInstance | nindent 4 }}
