apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-npmrc
  labels:
    app.kubernetes.io/name: jenkins
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.configMap.npmrc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  .npmrc: | {{ .Values.configMap.npmrc.registrySettings | nindent 4 }}