apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: jenkins-maven-settings
  labels:
    app.kubernetes.io/name: jenkins
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- with .Values.secret.mavenSettings.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.secret.mavenSettings.annotations }}
  annotations: {{ toYaml .Values.secret.mavenSettings.annotations | nindent 4 }}
  {{- end }}
stringData:
  settings.xml: | {{ .Values.secret.mavenSettings.xmlSettings | nindent 4 }}