apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nexus.name" . }}
  labels:
    "app.kubernetes.io/name": {{ template "nexus.fullname" . }}
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
    jenkins.io/credentials-type: usernamePassword
  annotations:
    "meta.helm.sh/release-name": "{{ .Release.Name }}"
    "meta.helm.sh/release-namespace": {{ .Values.namespace }}
type: Opaque
data:  
  username: {{ default .Values.secret.defaultUsername .Values.secret.username | b64enc | quote }}
  password: {{ default .Values.secret.defaultPassword .Values.secret.password | b64enc | quote }}
