apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.docker.name }}
  labels:
    "app.kubernetes.io/name": {{ template "nexus.fullname" . }}
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
  annotations:
    "meta.helm.sh/release-name": "{{ .Release.Name }}"
    "meta.helm.sh/release-namespace": {{ .Values.namespace }}
{{- if .Values.docker.service.annotations }}
{{ toYaml .Values.docker.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.docker.service.type }}
  ports:
  - name: {{ .Values.docker.service.name }}
    port: {{ .Values.docker.service.externalPort }}
    targetPort: {{ .Values.docker.service.internalPort }}
    protocol: {{ .Values.docker.service.protocol }}
  selector:
    app: {{ template "nexus.name" . }}
    release: {{ .Release.Name }}
