# used to generate an ingress for nexus and chartmuseum
expose:
  config:
    domain: dev.nuxeo.com
    exposer: Ingress
    http: true
    tlsacme: true
    tlsSecretName: $NAMESPACE-tls
    urltemplate: '"{{.Service}}.{{.Namespace}}.{{.Domain}}"'
# jenkins is handled by helmfile.yaml
jenkins:
  enabled: false
# Docker registry is handled by nexus
docker-registry:
  enabled: false
nexus:
  image:
    repository: gcr.io/jenkinsxio/nexus
    tag: 0.1.36
  env:
    # Fix system status warning about available CPUs: "The host system is allocating a maximum of 1 cores to the application. A minimum of 4 is recommended.",
    # by specifying the active processor count.
    # The rest is copied from the Sonatype image: https://github.com/sonatype/docker-nexus3/blob/b2a9af6d44348584087cbc0795399c256b36e729/Dockerfile.rh.centos#L75.
    INSTALL4J_ADD_VM_PARAMS: "-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=/nexus-data/javaprefs -XX:ActiveProcessorCount=4"
  persistence:
    size: 310Gi
    storageClass: standard
PipelineSecrets:
  DockerConfig: |-
    $DOCKER_REGISTRY_CONFIG
