# used to generate an ingress for nexus and chartmuseum
expose:
  Image: "ghcr.io/jenkins-x/exposecontroller"
  ImageTag: "2.3.118"
  config:
    domain: dev.nuxeo.com
    exposer: Ingress
    http: true
    tlsacme: true
    tlsSecretName: $NAMESPACE-tls
    urltemplate: '"{{.Service}}.{{.Namespace}}.{{.Domain}}"'
# jenkins is handled by helmfile.yaml
jenkins:
  enabled: false
# Docker registry is handled by nexus
docker-registry:
  enabled: false
nexus:
  image:
    repository: ghcr.io/jenkins-x/nexus
    tag: 0.1.41
  env:
    # Fix system status warning about available CPUs: "The host system is allocating a maximum of 1 cores to the application. A minimum of 4 is recommended.",
    # by specifying the active processor count.
    # The rest is copied from the Sonatype image: https://github.com/sonatype/docker-nexus3/blob/b2a9af6d44348584087cbc0795399c256b36e729/Dockerfile.rh.centos#L75.
    INSTALL4J_ADD_VM_PARAMS: "-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=/nexus-data/javaprefs -XX:ActiveProcessorCount=4"
  persistence:
    size: 310Gi
    storageClass: standard
chartmuseum:
  # Fix long volume attach/mount times
  # See https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/README.md#long-volume-attachmount-times
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    supplementalGroups:
    - 1000
  nodeSelector:
    team: platform
  tolerations:
  - key: team
    operator: Equal
    value: platform
    effect: NoSchedule
controllerrole:
  image:
    repository: ghcr.io/jenkins-x/builder-jx
    tag: 2.1.155-779-patch2
  nodeSelector:
    team: platform
  tolerations:
  - key: team
    operator: Equal
    value: platform
    effect: NoSchedule
PipelineSecrets:
  DockerConfig: |-
    $DOCKER_REGISTRY_CONFIG
